name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $GITHUB_WORKSPACE/Demo.Blazor.Auth0/Demo.Blazor.Auth0.SS.WebApp/Dockerfile --tag demo-blazor-auth0-ss-webapp:$(date +%s)
